// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrklIcRg85TS8ARkUIwPtjj28voE45IQ',
    appId: '1:433582598560:web:aff8d91bd122f11908dcc5',
    messagingSenderId: '433582598560',
    projectId: 'quick-fix-89d7f',
    authDomain: 'quick-fix-89d7f.firebaseapp.com',
    storageBucket: 'quick-fix-89d7f.firebasestorage.app',
    measurementId: 'G-5J1B2Y7V0B',
    databaseURL:
        'https://quick-fix-89d7f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZwoNzhaT0gXOWXkG9pCy2lwjYu1xlgo',
    appId: '1:433582598560:android:6d080feb733d77cb08dcc5',
    messagingSenderId: '433582598560',
    projectId: 'quick-fix-89d7f',
    storageBucket: 'quick-fix-89d7f.firebasestorage.app',
    databaseURL:
        'https://quick-fix-89d7f-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5lywjoba0CkyAeOzFGGOAKx7GO2WALPg',
    appId: '1:433582598560:ios:f0221c7dd92a142f08dcc5',
    messagingSenderId: '433582598560',
    projectId: 'quick-fix-89d7f',
    storageBucket: 'quick-fix-89d7f.firebasestorage.app',
    iosBundleId: 'com.example.quickFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5lywjoba0CkyAeOzFGGOAKx7GO2WALPg',
    appId: '1:433582598560:ios:f0221c7dd92a142f08dcc5',
    messagingSenderId: '433582598560',
    projectId: 'quick-fix-89d7f',
    storageBucket: 'quick-fix-89d7f.firebasestorage.app',
    iosBundleId: 'com.example.quickFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrklIcRg85TS8ARkUIwPtjj28voE45IQ',
    appId: '1:433582598560:web:01201b5211c0be8b08dcc5',
    messagingSenderId: '433582598560',
    projectId: 'quick-fix-89d7f',
    authDomain: 'quick-fix-89d7f.firebaseapp.com',
    storageBucket: 'quick-fix-89d7f.firebasestorage.app',
    measurementId: 'G-ZD2VR58ZKH',
  );
}
